name: Updater CI

on: workflow_dispatch
permissions: write-all
env:
  HUSKY: 0
  PUBLIC_RELEASE_REPO: pius-pp/celestial-mihomo-client-public

jobs:
  release-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          run_install: false

      - name: Pnpm install
        run: pnpm i

      - name: Release updater file
        run: pnpm updater
        env:
          PUBLIC_RELEASE_REPO: ${{ env.PUBLIC_RELEASE_REPO }}
          PUBLIC_RELEASE_TOKEN: ${{ secrets.PUBLIC_RELEASE_TOKEN }}

  release-update-for-fixed-webview2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          run_install: false

      - name: Pnpm install
        run: pnpm i

      - name: Release updater file
        run: pnpm updater-fixed-webview2
        env:
          PUBLIC_RELEASE_REPO: ${{ env.PUBLIC_RELEASE_REPO }}
          PUBLIC_RELEASE_TOKEN: ${{ secrets.PUBLIC_RELEASE_TOKEN }}
